### ISSUE TITLE
Automated API Documentation

### ISSUE THREAD

**Issue by StefanJum** [unikraft/unikraft#558]
### Feature request summary

This issue tracks the addition of code comments to each internal library to be ultimately retrieved and displayed on the Unikraft OSS project website (e.g. Doxygen style). Each item represents an issue to be resolved as a PR which adds the code comments to the corresponding library.
For an example of how the code should look like, you can check some of Unikraft's well documented internal libraries headers (e.g. [uktest](https://github.com/unikraft/unikraft/blob/staging/lib/uktest/include/uk/test.h), [ukstore](https://github.com/unikraft/unikraft/blob/staging/lib/ukstore/include/uk/store.h), etc).

- [ ] Add Doxygen style code comments for `9pfs`
-  #714 
- [ ] Add Doxygen style code comments for `fdt`
- [ ] Add Doxygen style code comments for `isrlib`
- [ ] Add Doxygen style code comments for `nolibc`
- [ ] Add Doxygen style code comments for `posix-event`
- [x] Add Doxygen style code comments for `posix-futex`
- [ ] Add Doxygen style code comments for `posix-libdl`
- [ ] Add Doxygen style code comments for `posix-process`
- [x] Add Doxygen style code comments for `posix-socket`
- [ ] Add Doxygen style code comments for `posix-sysinfo`
- [ ] Add Doxygen style code comments for `posix-user`
-  #704  
- [x] Add Doxygen style code comments for `syscall_shim`
- [ ] Add Doxygen style code comments for `ubsan`
- [x] Add Doxygen style code comments for `uk9p`
- [ ] Add Doxygen style code comments for `ukalloc`
- [ ] Add Doxygen style code comments for `ukallocbbuddy`
- [x] Add Doxygen style code comments for `ukallocpool`
- [ ] Add Doxygen style code comments for `ukallocregion`
- [ ] Add Doxygen style code comments for `ukargparse`
- [x] Add Doxygen style code comments for `ukblkdev`
- [ ] Add Doxygen style code comments for `ukboot`
- [ ] Add Doxygen style code comments for `ukbus`
- [x] Add Doxygen style code comments for `ukcpio`
- [ ] Add Doxygen style code comments for `ukcpuid`
- [ ] Add Doxygen style code comments for `ukdebug`
- [x] Add Doxygen style code comments for `ukfalloc`
- [x] Add Doxygen style code comments for `ukfallocbuddy`
- [x] Add Doxygen style code comments for `uklibparam`
- [ ] Add Doxygen style code comments for `uklock`
- [ ] Add Doxygen style code comments for `ukmmap`
- [ ] Add Doxygen style code comments for `ukmpi`
- [x] Add Doxygen style code comments for `uknetdev`
- [ ] Add Doxygen style code comments for `ukrand`
- [ ] Add Doxygen style code comments for `ukring`
- [ ] Add Doxygen style code comments for `ukrust`
-  #708 
- [ ] Add Doxygen style code comments for `ukschedcoop`
- [x] Add Doxygen style code comments for `uksglist`
- [ ] Add Doxygen style code comments for `uksignal`
- [ ] Add Doxygen style code comments for `uksp`
- [x] Add Doxygen style code comments for `ukstore`
- [ ] Add Doxygen style code comments for `ukswrand`
- [x] Add Doxygen style code comments for `uktest`
- [ ] Add Doxygen style code comments for `uktime`
- [ ] Add Doxygen style code comments for `uktimeconv`
-  #707

**Comment by allisoncchen** [comment]
Hi! I'm a student at UT Austin currently taking a virtualization course – would it be alright if I began working through the documentation checklist? I'll be working on it with @kmxtn and @joecwilson.

**Comment by allisoncchen** [comment]
Hi! I just wanted to follow up on whether it would be alright if I began working through the documentation checklist!

**Comment by bhaaaav** [comment]
@StefanJum I'd like to work on this, can I go for it?
