### ISSUE TITLE
Unit Tests for Internal Libraries

### ISSUE THREAD

**Issue by razvand** [unikraft/unikraft#580]
### Feature request summary

Unit testing ensure a good quality of the implementation.
Existence of unit tests allows regression testing: any new feature will be validated with existing unit tests.
Add unit tests (using [uktest](https://unikraft.org/docs/develop/writing-tests/)) for [internal Unikraft libraries](https://github.com/unikraft/unikraft/tree/staging/lib).

Each item represents an issue to be resolved as a PR which introduces the relevant `tests/` folder and tests to the corresponding library.

```[tasklist]
- [ ] Introduce `tests/` for `9pfs`
- [ ] Introduce `tests/` for `devfs`
- [ ] Introduce `tests/` for `fdt`
- [ ] Introduce `tests/` for `isrlib`
- [ ] Introduce `tests/` for `nolibc`
- [ ] Introduce `tests/` for `posix-libdl`
- [ ] Introduce `tests/` for `posix-process`
- [ ] Introduce `tests/` for `posix-sysinfo`
- [ ] Introduce `tests/` for `posix-user`
- [ ] Introduce `tests/` for `ramfs`
- [ ] Introduce `tests/` for `syscall_shim`
- [ ] Introduce `tests/` for `ubsan`
- [ ] Introduce `tests/` for `uk9p`
- [ ] Introduce `tests/` for `ukalloc`
- [ ] Introduce `tests/` for `ukallocbbuddy`
- [ ] Introduce `tests/` for `ukallocpool`
- [ ] Introduce `tests/` for `ukallocregion`
- [x] Introduce `tests/` for `ukargparse`
- [ ] Introduce `tests/` for `ukblkdev`
- [ ] Introduce `tests/` for `ukboot`
- [ ] Introduce `tests/` for `ukbus`
- [ ] Introduce `tests/` for `ukcpio`
- [ ] Introduce `tests/` for `ukdebug`
- [ ] Introduce `tests/` for `ukfalloc`
- [ ] Introduce `tests/` for `ukfallocbuddy`
- [ ] Introduce `tests/` for `uklibparam`
- [ ] Introduce `tests/` for `uklock`
- [ ] Introduce `tests/` for `ukmmap`
- [ ] Introduce `tests/` for `ukmpi`
- [ ] Introduce `tests/` for `uknetdev`
- [ ] Introduce `tests/` for `ukrust`
- [ ] Introduce `tests/` for `uksched`
- [ ] Introduce `tests/` for `ukschedcoop`
- [ ] Introduce `tests/` for `uksglist`
- [ ] Introduce `tests/` for `uksignal`
- [ ] Introduce `tests/` for `uksp`
- [ ] Introduce `tests/` for `ukstore`
- [ ] Introduce `tests/` for `ukswrand`
- [ ] Introduce `tests/` for `uktest`
- [ ] Introduce `tests/` for `uktime`
- [ ] Introduce `tests/` for `uktimeconv`
- [ ] Introduce `tests/` for `vfscore`
```

**Comment by fabianpatras** [comment]
Cc-ing #596 as a blocker for `ukrust` lib.

**Comment by allisoncchen** [comment]
Hi! I'm a student at UT Austin currently taking a virtualization course – would it be alright if I began writing unit tests for some of the items listed above? I'll be working with @kmxtn and @joecwilson.

**Comment by allisoncchen** [comment]
Hi! I just wanted to follow up on my previous message of whether it would be alright if I began writing some unit tests!

**Comment by bhaaaav** [comment]
@razvand I'd like to work on this, is it still relevant?
